### ISSUE TITLE
App -Appointment created without professional

### ISSUE THREAD

**Issue by tayyibs** [heartbeatservice/HeartbeatServiceSolution#6]
I was able to create and save an appointment without selecting a professional.

**Comment by tayyibs** [comment]
This has not been fixed. I am still able to create an appointment without selecting a professional.

Steps to replicate:
1.) Go to Calender and double click in any date box without selecting a professional. 
2.) Enter the title and customer and click save.
3.) The appointment saves successfully. The record is saved with professional ID 0 in the database.

Expected behavior:
The appointment  should not save and prompt for the professional name before saving.

@umais  @naveed84n

**Comment by akhan0** [comment]
It is verified and it is showing the alert message saying "Please select customer", you can try by clearing cache of browser because it might be loading the previous java script file.
@umais @naveed84n

![6](https://cloud.githubusercontent.com/assets/11011123/6880503/dc433962-d556-11e4-8fd9-02a523be8412.png)

**Comment by tayyibs** [comment]
Customer validation is fine, its the professional validation that is not working. The appointment is being created under a dummy Doctor(professional).

**Comment by akhan0** [comment]
Please check it with new record, it is fixed now.

**Comment by Raheelsid** [comment]
not able to make appointment without selecting professional .... validation was applied
