### ISSUE TITLE
Cust-Customer Search Page doesn't have paging

### ISSUE THREAD

**Issue by naveed84n** [heartbeatservice/HeartbeatServiceSolution#8]
The customer search page when you do an open search doesn't have paging and you have to scroll all the way through

**Comment by amirsaleem** [comment]
Umais and I talked about this bug and conclude that this is not a bug and should be taken as an low priority enhancement because paging is not necessary on search grid and if user need to search for customer etc they weren't be too many.  At this point what we can do is that  create another defect to remove  wild search that brings every customer when search box is empty.

**Comment by heartbeatservice** [comment]
Sure , I am okay with this ...not a big deal

**Comment by tayyibs** [comment]
verified. Customer search page now has paging.
